### ISSUE TITLE
Fix 500 error when user connect to steemkr at the biginning

### ISSUE THREAD

**Issue by woogenius** [steemKR/issues#12]

**Comment by wooklym** [comment]
PostFull, Comment 에서 transformContent 펑션 호출하는데, 최초 접속 시 그 안에 location 이 정의되지 않아서 500에러 발생. location 값을 펑션에 전달 하는 등 다른 방법 찾아서 해결하도록 하겠음.

**Comment by wooklym** [comment]
done. https://github.com/steemKR/condenser/commit/bfc1f6ff276af014ae61ee9347ce379c850bc654
