### ISSUE TITLE
Translate it to korean

### ISSUE THREAD

**Issue by woogenius** [steemKR/issues#5]
한국어로 번역하기 버튼!

**Comment by sneak** [comment]
I suggest that you contribute your contributions directly to the main condenser repository - we are happy to merge in additional translations. :)

**Comment by woogenius** [comment]
@sneak Actually this issue is for making additional button to translate post, comment to korean. We've done some l18n work on this repo, we will make a PR to merge this change to main repo soon!

Also we are happy to make a PR with this feature after testing is done on our side.

Thanks!!

**Comment by woogenius** [comment]
Done
